package com.koowo.entity.paycenter;



/**
 * AutoCount generated by MyEclipse - Hibernate Tools
 */

public class AutoCount  implements java.io.Serializable {


    // Fields    

     private Integer id;


    // Constructors

    /** default constructor */
    public AutoCount() {
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
   








}