package com.koowo.entity.paycenter;



/**
 * Account generated by MyEclipse - Hibernate Tools
 */

public class AwardFlag  implements java.io.Serializable {
	
	public static final int STATE_HASGOT=1;
	public static final int STATE_NOTGOT=0;
	
   private Long id;
   private Long accountId;
   private Long cash;
   private Integer gid;
   private Integer state;
public Long getAccountId() {
	return accountId;
}
public void setAccountId(Long accountId) {
	this.accountId = accountId;
}
public Integer getGid() {
	return gid;
}
public void setGid(Integer gid) {
	this.gid = gid;
}
public Long getId() {
	return id;
}
public void setId(Long id) {
	this.id = id;
}
public Integer getState() {
	return state;
}
public void setState(Integer state) {
	this.state = state;
}
public Long getCash() {
	return cash;
}
public void setCash(Long cash) {
	this.cash = cash;
}
    
}