package com.koowo.entity.paycenter;

import java.util.Date;


/**
 * GameServer generated by MyEclipse - Hibernate Tools
 */

public class GameServer  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Long gid;
     private Integer sid;
     private String sname;
     private Short state;
     private Short serveracting;
     private Date activeTime;
     private String serverOwner;
     private String generalizeDays;
     private String generalizeArea;
     private String remark;


	public String getGeneralizeDays() {
		return generalizeDays;
	}


	public void setGeneralizeDays(String generalizeDays) {
		this.generalizeDays = generalizeDays;
	}


	public String getGeneralizeArea() {
		return generalizeArea;
	}


	public void setGeneralizeArea(String generalizeArea) {
		this.generalizeArea = generalizeArea;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	/** default constructor */
    public GameServer() {
    }

    
    public GameServer(Long gid, Integer sid, String sname) {
		this.gid = gid;
		this.sid = sid;
		this.sname = sname;
	}


	/** full constructor */
    public GameServer(Long gid, Integer sid, String sname, Short state) {
        this.gid = gid;
        this.sid = sid;
        this.sname = sname;
        this.state = state;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Long getGid() {
        return this.gid;
    }
    
    public void setGid(Long gid) {
        this.gid = gid;
    }

    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }

    public Short getState() {
        return this.state;
    }
    
    public void setState(Short state) {
        this.state = state;
    }


	public Short getServeracting() {
		return serveracting;
	}


	public void setServeracting(Short serveracting) {
		this.serveracting = serveracting;
	}


	public Date getActiveTime() {
		return activeTime;
	}


	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}


	public String getServerOwner() {
		return serverOwner;
	}


	public void setServerOwner(String serverOwner) {
		this.serverOwner = serverOwner;
	}
}