package com.koowo.entity.paycenter;

import java.util.Date;


/**
 * GiftGetLog generated by MyEclipse - Hibernate Tools
 */

public class GiftGetLog  implements java.io.Serializable {

	public static Integer STATE_NORMAL = new Integer("0");
	public static Integer DHQ_STATE_NORMAL = new Integer("9");
	//为了保持之前的现金券逻辑不便,并增加兑换券类型,故现金券的状态设置为9 gid为4
	 
    // Fields    

     private Long id;
     private Long accountId;
     private Long giftId;
     private Long cash;
     private Date establishTime;
     private Integer state;
     private String comments;


    // Constructors

    /** default constructor */
    public GiftGetLog() {
    }

	/** minimal constructor */
    public GiftGetLog(Long accountId, Long giftId, Long cash, Date establishTime, Integer state) {
        this.accountId = accountId;
        this.giftId = giftId;
        this.cash = cash;
        this.establishTime = establishTime;
        this.state = state;
    }
    
    /** full constructor */
    public GiftGetLog(Long accountId, Long giftId, Long cash, Date establishTime, Integer state, String comments) {
        this.accountId = accountId;
        this.giftId = giftId;
        this.cash = cash;
        this.establishTime = establishTime;
        this.state = state;
        this.comments = comments;
    }

    /**
     * 日志格式输出
     * @return
     */
    public String asLogString(){
    	StringBuffer sb = new StringBuffer();
    	sb.append("get gift:");
    	sb.append(this.accountId.longValue());
    	sb.append(" get ");
    	sb.append(this.cash.longValue());
    	sb.append(" gift ");
    	sb.append(this.giftId.longValue());
    	sb.append("|");
    	return sb.toString();
    }
   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public Long getGiftId() {
        return this.giftId;
    }
    
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    public Long getCash() {
        return this.cash;
    }
    
    public void setCash(Long cash) {
        this.cash = cash;
    }

    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
   








}