package com.koowo.entity.paycenter;



/**
 * PayAdmin generated by MyEclipse - Hibernate Tools
 */

public class PayAdmin  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String userName;
     private String password;
     private String permissionId;
     private String opGame;
     private Long parentId;//父id
     private int state;//0 :正常 1:账户停用
     private String remark;//登陆用户的真是姓名

	/** minimal constructor */
    public PayAdmin(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }
    
    /** full constructor */
    public PayAdmin(String userName, String password, String permissionId) {
        this.userName = userName;
        this.password = password;
        this.permissionId = permissionId;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

	public String getOpGame() {
		return opGame;
	}

	public void setOpGame(String opGame) {
		this.opGame = opGame;
	}

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
   








}