package com.koowo.entity.paycenter;

import java.math.BigDecimal;
import java.util.Date;


/**
 * PayOrder generated by MyEclipse - Hibernate Tools
 */

public class PayOrder  implements java.io.Serializable {

	//待处理
	public static Integer STATE_WAIT =  new Integer("0");
	//已成功
	public static Integer STATE_USED = new Integer("1");
	//管理员手动处理
	public static Integer STATE_ADMIN_MOD =  new Integer("2");

    // Fields    

     private Long id;
     private Long accountId;
     private Long fromAccountId;
     private String orderId;
     private String channel;
     private BigDecimal cash;
     private Date establishTime;
     private Integer state;
     private String useGame;
     private String useServer;
     private String useOrder;
     private BigDecimal useKwb;
     
     private String serviceName;
     private Long serviceId;
     
     private String ext1;
     private String ext2;
     
     private String role;

    // Constructors

    public String getExt1() {
		return ext1;
	}


	public void setExt1(String ext1) {
		this.ext1 = ext1;
	}


	public String getExt2() {
		return ext2;
	}


	public void setExt2(String ext2) {
		this.ext2 = ext2;
	}


	/** default constructor */
    public PayOrder() {
    }

    
    /** full constructor */
    public PayOrder(Long accountId, String orderId, String channel, BigDecimal cash, Date establishTime, Integer state) {
        this.accountId = accountId;
        this.orderId = orderId;
        this.channel = channel;
        this.cash = cash;
        this.establishTime = establishTime;
        this.state = state;
    }
    
    /**
     * 将PayOrder信息中的某几项作为一行，方便往文件中写
     * @return
     */
    public String toStringForAliCheck() {
		String orderId = this.orderId.toString();
		String cash = this.cash.toString();
		return orderId + "\t" + cash;
	}
   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }

    public BigDecimal getCash() {
        return this.cash;
    }
    
    public void setCash(BigDecimal cash) {
        this.cash = cash;
    }

    public Date getEstablishTime() {
        return this.establishTime;
    }
    
    public void setEstablishTime(Date establishTime) {
        this.establishTime = establishTime;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }


	public String getUseGame() {
		return useGame;
	}


	public void setUseGame(String useGame) {
		this.useGame = useGame;
	}


	public String getUseOrder() {
		return useOrder;
	}


	public void setUseOrder(String useOrder) {
		this.useOrder = useOrder;
	}


	public String getUseServer() {
		return useServer;
	}


	public void setUseServer(String useServer) {
		this.useServer = useServer;
	}


	public BigDecimal getUseKwb() {
		return useKwb;
	}


	public void setUseKwb(BigDecimal useKwb) {
		this.useKwb = useKwb;
	}


	public Long getServiceId() {
		return serviceId;
	}


	public void setServiceId(Long serviceId) {
		this.serviceId = serviceId;
	}


	public String getServiceName() {
		return serviceName;
	}


	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}


	public String getRole() {
		return role;
	}


	public void setRole(String role) {
		this.role = role;
	}


	public Long getFromAccountId() {
		return fromAccountId;
	}
	
	public void setFromAccountId(Long fromAccountId) {
		this.fromAccountId = fromAccountId;
	}
}