package com.koowo.entity.paycenter;



/**
 * PayPermission generated by MyEclipse - Hibernate Tools
 */

public class PayPermission  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Integer pid;
     private String title;
     private String link;
     private Integer PType;


    // Constructors

    /** default constructor */
    public PayPermission() {
    }

    
    /** full constructor */
    public PayPermission(String title, String link, Integer PType) {
        this.title = title;
        this.link = link;
        this.PType = PType;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    public Integer getPType() {
        return this.PType;
    }
    
    public void setPType(Integer PType) {
        this.PType = PType;
    }


	public Integer getPid() {
		return pid;
	}


	public void setPid(Integer pid) {
		this.pid = pid;
	}
   








}