package com.koowo.entity.paycenter;

import org.json.simple.JSONObject;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Renewal generated by MyEclipse - Hibernate Tools
 */

public class Renewal implements java.io.Serializable {

	// 待处理
	public static Integer STATE_WAIT = new Integer("0");
	// 已成功
	public static Integer STATE_USED = new Integer("1");
	// 已提交到渠道放
	public static Integer STATE_HAS_SUBMITTED = new Integer("2");
	// 失败
	public static Integer STATE_FAILED = new Integer("3");

	// Fields

	private Long id;
	private Long uid;
	private String certificate;
	private String customerId;
	private String orderId;
	private String channel;
	private Date establishTime;
	private Date finishTime;
	private Integer state;
	private BigDecimal cash;
	private String serviceName;
	private String type;
	private Long serviceId;
	private String ext;

	/** default constructor */
	public Renewal() {
	}

	public JSONObject toJSON() {
		JSONObject jo = new JSONObject();
		jo.put("id", this.getId());
		jo.put("uid", this.getUid());
		jo.put("certificate", this.getCertificate());
		jo.put("customerId", this.getCustomerId());
		jo.put("orderId", this.getOrderId());
		jo.put("channel", this.getChannel());
		Date establishDate = this.getEstablishTime();
		SimpleDateFormat ymdhms = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		String establishTimeStr = ymdhms.format(establishDate);
		jo.put("establishTime", establishTimeStr);
		jo.put("state", this.getState());
		jo.put("cash", this.getCash());
		Long serviceIdLong = this.getServiceId();
		String serviceIdStr = "";
		if (serviceIdLong != null) {
			serviceIdStr = String.valueOf(serviceIdLong);
		}
		jo.put("serviceId", serviceIdStr);
		return jo;
		
	}
	public static Integer getSTATE_WAIT() {
		return STATE_WAIT;
	}

	public static void setSTATE_WAIT(Integer sTATE_WAIT) {
		STATE_WAIT = sTATE_WAIT;
	}

	public static Integer getSTATE_USED() {
		return STATE_USED;
	}

	public static void setSTATE_USED(Integer sTATE_USED) {
		STATE_USED = sTATE_USED;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUid() {
		return uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getCertificate() {
		return certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public Date getEstablishTime() {
		return establishTime;
	}

	public void setEstablishTime(Date establishTime) {
		this.establishTime = establishTime;
	}

	public Date getFinishTime() {
		return finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public BigDecimal getCash() {
		return cash;
	}

	public void setCash(BigDecimal cash) {
		this.cash = cash;
	}

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getServiceId() {
		return serviceId;
	}

	public void setServiceId(Long serviceId) {
		this.serviceId = serviceId;
	}

	public String getExt() {
		return ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

}