package com.koowo.entity.paycenter;

import java.util.Date;


/**
 * PayLog generated by MyEclipse - Hibernate Tools
 */

public class SignAlipay  implements java.io.Serializable {

	//记录状态
	//已经正常结束的记录
	public static Integer STATE_NORMAL = new Integer("1");
	//正在等待签约的记录
	public static Integer STATE_WAIT = new Integer("0");
	
	//协议名（一键支付）
	public static final String ALIPAY_PROTOCOL = "b2c_charge"; 

    // Fields    

	private Long id;
	private Long accountId;
	private String protocol;
	private String signNo;
	private Date signDate;
	private String userSignNo;
	private String userAccountNo;
	private String alipayUserId;
	private String userLogonId;
	private int state;
	private String serviceStartDate;
	private String serviceEndDate;
	private String serviceName;
	private String ext;
	private String orderId;
	

    public SignAlipay() {
    }
    
    public String toString() {
    	return "accountId=" + accountId + ",protocol=" + protocol + ",signNo=" + signNo + ",userSignNo=" + userSignNo + ",state=" + state + ",serviceStartDate=" + serviceStartDate +
    			",alipayUserId=" + alipayUserId + ",serviceName=" + serviceName;
    }

	public SignAlipay(Long id, Long accountId, String protocol, String signNo,
			Date signDate, String userSignNo, String userAccountNo,
			String alipayUserId, String userLogonId, int state,
			String serviceStartDate, String serviceEndDate, String ext, String serviceName, String orderId) {
		super();
		this.id = id;
		this.accountId = accountId;
		this.protocol = protocol;
		this.signNo = signNo;
		this.signDate = signDate;
		this.userSignNo = userSignNo;
		this.userAccountNo = userAccountNo;
		this.alipayUserId = alipayUserId;
		this.userLogonId = userLogonId;
		this.state = state;
		this.serviceStartDate = serviceStartDate;
		this.serviceEndDate = serviceEndDate;
		this.serviceName = serviceName;
		this.ext = ext;
		this.orderId = orderId;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public Long getAccountId() {
		return accountId;
	}


	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}


	public String getProtocol() {
		return protocol;
	}


	public void setProtocol(String protocol) {
		this.protocol = protocol;
	}


	public String getSignNo() {
		return signNo;
	}


	public void setSignNo(String signNo) {
		this.signNo = signNo;
	}


	public Date getSignDate() {
		return signDate;
	}


	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}


	public String getUserSignNo() {
		return userSignNo;
	}


	public void setUserSignNo(String userSignNo) {
		this.userSignNo = userSignNo;
	}


	public String getUserAccountNo() {
		return userAccountNo;
	}


	public void setUserAccountNo(String userAccountNo) {
		this.userAccountNo = userAccountNo;
	}


	public String getAlipayUserId() {
		return alipayUserId;
	}


	public void setAlipayUserId(String alipayUserId) {
		this.alipayUserId = alipayUserId;
	}


	public String getUserLogonId() {
		return userLogonId;
	}


	public void setUserLogonId(String userLogonId) {
		this.userLogonId = userLogonId;
	}


	public int getState() {
		return state;
	}


	public void setState(int state) {
		this.state = state;
	}


	public String getServiceStartDate() {
		return serviceStartDate;
	}


	public void setServiceStartDate(String serviceStartDate) {
		this.serviceStartDate = serviceStartDate;
	}


	public String getServiceEndDate() {
		return serviceEndDate;
	}


	public void setServiceEndDate(String serviceEndDate) {
		this.serviceEndDate = serviceEndDate;
	}


	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getExt() {
		return ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}
	
	public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    
}